In [ ]:
import pandas as pd
import numpy as np

df= pd.read_csv("ecommerce_customer_behavior_dataset_v2.csv")

In [ ]:
df.shape

(17049, 18)

In [ ]:
df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_000001-1,CUST_00001,2023-05-29,40,Male,Ankara,Books,29.18,1,0.00,29.18,Digital Wallet,Mobile,14,9,True,13,4
1,ORD_000001-2,CUST_00001,2023-10-12,40,Male,Ankara,Home & Garden,644.40,1,138.05,506.35,Credit Card,Desktop,14,8,True,6,2
2,ORD_000001-3,CUST_00001,2023-12-05,40,Male,Ankara,Sports,332.82,5,0.00,1664.10,Credit Card,Mobile,15,10,True,9,4
3,ORD_000002-1,CUST_00002,2023-05-11,33,Male,Istanbul,Food,69.30,5,71.05,275.45,Digital Wallet,Desktop,16,13,True,4,4
4,ORD_000002-2,CUST_00002,2023-06-16,33,Male,Istanbul,Beauty,178.15,3,0.00,534.45,Credit Card,Mobile,14,7,True,6,4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17049 entries, 0 to 17048
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  17049 non-null  object
 1   Customer_ID               17049 non-null  object
 2   Date                      17049 non-null  object
 3   Age                       17049 non-null  int64
 4   Gender                    17049 non-null  object
 5   City                      17049 non-null  object
 6   Product_Category          17049 non-null  object
 7   Unit_Price                17049 non-null  float64
 8   Quantity                  17049 non-null  int64
 9   Discount_Amount           17049 non-null  float64
 10  Total_Amount              17049 non-null  float64
 11  Payment_Method            17049 non-null  object
 12  Device_Type               17049 non-null  object
 13  Session_Duration_Minutes  17049 non-null  int64
 14  Pages_Viewed              17049 non-null  int64
 15  Is_Returning_Customer     17049 non-null  bool
 16  Delivery_Time_Days        17049 non-null  int64
 17  Customer_Rating           17049 non-null  int64
dtypes: bool(1), float64(3), int64(6), object(8)
memory usage: 2.2+ MB

In [ ]:
df.describe()

,Age,Unit_Price,Quantity,Discount_Amount,Total_Amount,Session_Duration_Minutes,Pages_Viewed,Delivery_Time_Days,Customer_Rating
count,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000
mean,34.945745,447.901689,3.011379,69.788135,1277.438711,14.535633,9.003109,6.503607,3.899408
std,11.046855,722.319705,1.417027,240.704662,2358.436375,2.925524,2.259954,3.488787,1.128803
min,18.000000,5.050000,1.000000,0.000000,6.210000,4.000000,1.000000,1.000000,1.000000
25%,26.000000,73.260000,2.000000,0.000000,172.970000,13.000000,7.000000,4.000000,3.000000
50%,35.000000,174.680000,3.000000,0.000000,455.850000,15.000000,9.000000,6.000000,4.000000
75%,42.000000,494.570000,4.000000,32.710000,1267.750000,17.000000,11.000000,8.000000,5.000000
max,75.000000,7900.010000,5.000000,6538.290000,37852.050000,26.000000,18.000000,25.000000,5.000000

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Order_ID'].duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.isnull().sum()

Order_ID                    0
Customer_ID                 0
Date                        0
Age                         0
Gender                      0
City                        0
Product_Category            0
Unit_Price                  0
Quantity                    0
Discount_Amount             0
Total_Amount                0
Payment_Method              0
Device_Type                 0
Session_Duration_Minutes    0
Pages_Viewed                0
Is_Returning_Customer       0
Delivery_Time_Days          0
Customer_Rating             0
dtype: int64

In [ ]:
df['Date']=pd.to_datetime(df['Date'])

In [ ]:
text_cols = ['Gender', 'City', 'Product_Category', 'Payment_Method', 'Device_Type']
for col in text_cols:
    df[col] = df[col].str.strip().str.title()

df['City'].unique()
df['Product_Category'].unique()

array(['Books', 'Home & Garden', 'Sports', 'Food', 'Beauty', 'Toys',
       'Fashion', 'Electronics'], dtype=object)

In [ ]:
df[df['Age'] < 10]                    # unrealistic ages
df[df['Unit_Price'] <= 0]             # zero/negative prices
df[df['Quantity'] <= 0]
df[df['Delivery_Time_Days'] > 30]     # extreme delivery delays
df[df['Customer_Rating'].between(1,5) == False]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Date, Age, Gender, City, Product_Category, Unit_Price, Quantity, Discount_Amount, Total_Amount, Payment_Method, Device_Type, Session_Duration_Minutes, Pages_Viewed, Is_Returning_Customer, Delivery_Time_Days, Customer_Rating]
Index: []

In [ ]:
df['expected_total'] = df['Unit_Price'] * df['Quantity'] - df['Discount_Amount']
mismatch = df[abs(df['expected_total'] - df['Total_Amount']) > 0.01]
mismatch.shape

(0, 19)

In [ ]:
df['Order_Month'] = df['Date'].dt.to_period('M').astype(str)
df['Age_Group'] = pd.cut(df['Age'], bins=[17,25,35,45,55,100],
                          labels=['18-25','26-35','36-45','46-55','56+'])

In [ ]:
df.drop(columns=['expected_total'], inplace=True)  # drop helper column
df.to_csv('ecommerce_cleaned.csv', index=False)

In [ ]:
from google.colab import files
files.download("ecommerce_cleaned.csv")

In [ ]:
import os
os.listdir()

['.config',
 'ecommerce_cleaned.csv',
 'ecommerce_customer_behavior_dataset_v2.csv',
 'sample_data']